### ISSUE TITLE
Is a virtual machine a good test system?

### ISSUE THREAD

**Issue by Flockenmumie** [IAIK/cache_template_attacks#12]
Thank you for providing this code! I was looking for implementation examples for educative purposes. Yet one thing didn't get from reading the papers:

"Use it only on test systems which contain no sensitive data." does it say in the Readme.md.

Can I try this on a virtual machine without any harm to the data on my host system?

Thank you very much in advance!

**Comment by dgruss** [comment]
Run the code at your own risk, no guarantees from my side.
