### ISSUE TITLE
openssl version for AES attack

### ISSUE THREAD

**Issue by agarwalayush** [IAIK/cache_template_attacks#2]
Hi,
Can you tell me which version of openssl did you use for the attach, as the new releases have a different implementation?

**Comment by dgruss** [comment]
There are barely any changes in the AES T-Table implementation of OpenSSL as it is usually not used anymore.
https://github.com/openssl/openssl/blame/master/crypto/aes/aes_x86core.c

**Comment by dgruss** [comment]
You can enable it in the OpenSSL code and compile it yourself...
