### ISSUE TITLE
error about make operation

### ISSUE THREAD

**Issue by yihong731** [IAIK/cache_template_attacks#3]
when cd calibration, and then
make
it comes some error as follow:

error inconsistent operand constraints in an ‘asm’

is there some wrong in the Makefile?

than you!

**Comment by yihong731** [comment]
debian 8.5
gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by dgruss** [comment]
can't reproduce this error... do you have more details?

**Comment by dgruss** [comment]
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609

**Comment by dgruss** [comment]
is this a 32bit system? i'm not sure this will work on a 32bit system...

**Comment by dgruss** [comment]
"The programs should work on x86-64 Intel CPUs independent of the operating system (as long as you can compile it). "

**Comment by yihong731** [comment]
The operation system: Debian GNU/Linux 8 (jessie) 32bit
The CPU:Intel® Core™ i5-4200U CPU @ 1.60GHz × 4

Thank you for your advices!

**Comment by dgruss** [comment]
On 19.09.2016 15:00, yihong731 wrote:
> The operation system: Debian GNU/Linux 8 (jessie) 32bit
> The CPU:Intel® Core™ i5-4200U CPU @ 1.60GHz × 4

Yes, to run it on a 32bit linux it's necessary to rewrite some inline 
assembly statements.

I would seriously recommend running a 64bit OS ;)

**Comment by yihong731** [comment]
yes. Now, my operation is 32bit, how can I rewrite the code?
just some inline code?
thank you!

**Comment by dgruss** [comment]
On 19.09.2016 15:53, yihong731 wrote:
> yes. Now, my operation is 32bit, how can I rewrite the code?

this is simple C/C++/inline-asm, I'm definitely not going into details here.

**Comment by dgruss** [comment]
On 19.09.2016 16:19, yihong731 wrote:
> I also want to run the code on ARM device, haha, have you try it before?

Has already been done.

See https://github.com/IAIK/armageddon

**Comment by yihong731** [comment]
Thank you for your help!
