### ISSUE TITLE
Some questions about the code, thx!

### ISSUE THREAD

**Issue by yihong731** [IAIK/cache_template_attacks#4]
Hi,
In the file: profiling\aes_example\spy.cpp
Why the key[] are all 0x00?
In the code line: “int fd = open("./libcrypto.so", O_RDONLY);”， is the libcrypto.so a special file which must be reloaded? Or can I replace it with other any .so file? 
The size of this file must can full reload in the L1 Cache or L2 Cache size?
What is the function of maccess(void *p)?

**Comment by dgruss** [comment]
On 21.09.2016 10:54, yihong731 wrote:
> In the file: profiling\aes_example\spy.cpp
> Why the key[] are all 0x00?

feel free to change the key.

> In the code line: “int fd = open("./libcrypto.so", O_RDONLY);”， is the
> libcrypto.so a special file which must be reloaded?

this is the code to attack the OpenSSL AES T-Table implementation, you 
need to compile that first.

> Or can I replace it with other any .so file?
> The size of this file must can full reload in the L1 Cache or L2 Cache size?
> What is the function of maccess(void *p)?

Read the source code ;)
