### ISSUE TITLE
Error in the command for keypresses

### ISSUE THREAD

**Issue by guilherme29** [IAIK/cache_template_attacks#9]
Hello,
Sorry to bother if what I'm saying is wrong but the command given in README.md for the keypresses is not working for me. the grep expression inside the \` \` is not working I think. You need the space after the ^ but then it will also get the space.

Here is possible solution to fix it:
$ cat /proc/\`ps -A | grep gedit | grep -oE "^ [0-9]+" | sed "s| ||g"\`/maps | grep r-x | grep gdk-3

This is probably not the best solution but I'm not really good with grep, just wanted to point out the mistake.

**Comment by dgruss** [comment]
Not sure, it works for me...
